spring:
  application:
    name: The system records the completed material
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/SRCM
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  messages:
    basename: message-center/messages, message-center/errors, message-center/warnings, message-center/logs
    fallback-to-system-locale: false

server:
  servlet:
    context-path: /api/v1

app:
  collage:
    base-url: https://www.lrmk.ru
    endpoints:
      pairs: /api/open/pairs
      rooms: /api/open/rooms
      groups: /api/open/groups
      weeks: /api/open/weeks
      teachers: /api/open/teachers
      subjects: /api/open/subjects
      timetable: /api/open/timetable
  file-path:
    groups: C:\Users\Radion\Documents\Test\Groups
    students: C:\Users\Radion\Documents\Test\Students

logging:
  level:
    radion.ru.srcm: debug
    root: info

